function [Amat,Bmat,Cmat,Dmat] = getLinearDynamics_at_k(in1,in2,in3)
%GETLINEARDYNAMICS_AT_K
%    [AMAT,BMAT,CMAT,DMAT] = GETLINEARDYNAMICS_AT_K(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    06-May-2018 19:54:53

A = in3(5,:);
B = in3(6,:);
C = in3(7,:);
Jz = in3(2,:);
a = in3(3,:);
b = in3(4,:);
delta = in2(2,:);
dt = in3(8,:);
m = in3(1,:);
psi = in1(6,:);
vx = in1(1,:);
vy = in1(2,:);
wz = in1(3,:);
t2 = 1.0./vx.^2;
t3 = a.*wz;
t4 = t3+vy;
t5 = 1.0./vx;
t6 = t4.*t5;
t7 = atan(t6);
t8 = delta-t7;
t9 = B.*t8;
t10 = atan(t9);
t11 = C.*t10;
t12 = cos(t11);
t13 = sin(delta);
t14 = t4.^2;
t15 = t2.*t14;
t16 = t15+1.0;
t17 = 1.0./t16;
t18 = a+b;
t19 = 1.0./t18;
t20 = B.^2;
t21 = t8.^2;
t22 = t20.*t21;
t23 = t22+1.0;
t24 = 1.0./t23;
t26 = b.*wz;
t25 = -t26+vy;
t27 = t5.*t25;
t28 = atan(t27);
t29 = 1.0./m;
t30 = B.*t28;
t31 = atan(t30);
t32 = C.*t31;
t33 = cos(t32);
t34 = t25.^2;
t35 = t2.*t34;
t36 = t35+1.0;
t37 = 1.0./t36;
t38 = t28.^2;
t39 = t20.*t38;
t40 = t39+1.0;
t41 = 1.0./t40;
t42 = cos(delta);
t43 = a.^2;
t44 = b.^2;
t45 = 1.0./Jz;
t46 = A.*B.*C.*m.*t5.*t19.*t33.*t37.*t41.*t44;
t47 = t46-A.*B.*C.*m.*t5.*t12.*t17.*t19.*t24.*t42.*t43;
t48 = cos(psi);
t49 = sin(psi);
t50 = dt.*t48;
Amat = reshape([A.*B.*C.*a.*dt.*t2.*t4.*t12.*t13.*t17.*t19.*t24.*2.0+1.0,-dt.*(wz+t29.*(A.*B.*C.*b.*m.*t2.*t19.*t25.*t33.*t37.*t41+A.*B.*C.*a.*m.*t2.*t4.*t12.*t17.*t19.*t24.*t42).*2.0),dt.*t45.*(A.*B.*C.*m.*t2.*t19.*t25.*t33.*t37.*t41.*t44-A.*B.*C.*m.*t2.*t4.*t12.*t17.*t19.*t24.*t42.*t43).*2.0,t50,dt.*t49,0.0,dt.*(wz-A.*B.*C.*a.*t5.*t12.*t13.*t17.*t19.*t24.*2.0),dt.*t29.*(A.*B.*C.*b.*m.*t5.*t19.*t33.*t37.*t41+A.*B.*C.*a.*m.*t5.*t12.*t17.*t19.*t24.*t42).*2.0+1.0,dt.*t45.*t47.*-2.0,-dt.*t49,t50,0.0,dt.*(vy-A.*B.*C.*t5.*t12.*t13.*t17.*t19.*t24.*t43.*2.0),-dt.*(vx+t29.*t47.*2.0),dt.*t45.*(A.*B.*C.*b.*m.*t5.*t19.*t33.*t37.*t41.*t44+A.*B.*C.*a.*m.*t5.*t12.*t17.*t19.*t24.*t42.*t43).*2.0+1.0,0.0,0.0,dt,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-dt.*(t49.*vx+t48.*vy),dt.*(t48.*vx-t49.*vy),1.0],[6,6]);
if nargout > 1
    t51 = sin(t11);
    Bmat = reshape([dt.*t29,0.0,0.0,0.0,0.0,0.0,dt.*(A.*a.*t19.*t42.*t51.*2.0+A.*B.*C.*a.*t12.*t13.*t19.*t24.*2.0),dt.*t29.*(A.*a.*m.*t13.*t19.*t51-A.*B.*C.*a.*m.*t12.*t19.*t24.*t42).*2.0,dt.*t45.*(A.*m.*t13.*t19.*t43.*t51-A.*B.*C.*m.*t12.*t19.*t24.*t42.*t43).*2.0,0.0,0.0,0.0],[6,2]);
end
if nargout > 2
    Cmat = reshape([1.0,-t29.*(A.*B.*C.*b.*m.*t2.*t19.*t25.*t33.*t37.*t41.*2.0+A.*B.*C.*a.*m.*t2.*t4.*t12.*t17.*t19.*t24.*t42.*2.0),0.0,0.0,t29.*(A.*B.*C.*b.*m.*t5.*t19.*t33.*t37.*t41.*2.0+A.*B.*C.*a.*m.*t5.*t12.*t17.*t19.*t24.*t42.*2.0),0.0,0.0,-t29.*(A.*B.*C.*m.*t5.*t19.*t33.*t37.*t41.*t44.*2.0-A.*B.*C.*m.*t5.*t12.*t17.*t19.*t24.*t42.*t43.*2.0),1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
end
if nargout > 3
    Dmat = reshape([0.0,0.0,0.0,0.0,t29.*(A.*a.*m.*t13.*t19.*t51.*2.0-A.*B.*C.*a.*m.*t12.*t19.*t24.*t42.*2.0),0.0],[3,2]);
end
